# -*- coding: utf-8 -*-
"""Prompt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13kMaU2HiSoWRe40T-MfrM1rdQQbNo4-7
"""

# prompts.py
from typing import Dict

INTRO = """You are an expert Excel interviewer and grader. Evaluate a candidate's answer for the given question.
Return a JSON object only (no explanation text) with keys:
- correctness: one of "correct", "partial", "incorrect"
- score: integer 0-10
- rationale: 1-2 sentence justification
- improvements: bullet list (max 3) of what to improve
- canonical_answer: concise example correct answer (<= 60 words)
- tags: list of tags like ["formula","vlookup","pivot","conditional_formatting","macro"]
"""

EVAL_RUBRIC = """
Scoring rubric:
- 9-10: Fully correct, succinct, shows best practice, mentions edge cases where relevant.
- 6-8: Mostly correct, minor omissions or slightly suboptimal approach.
- 3-5: Partial correctness, some relevant steps missing or incorrect formula.
- 0-2: Incorrect or no actual solution.
When awarding partial credit, indicate what's missing in 'improvements'.
"""

QUESTION_CONTEXT = {
    "q1": {
        "question": "How do you calculate the average of cells B1 through B20 in Excel? Provide the formula and mention what happens if some cells are blank or contain text.",
        "tags": ["formula","average"]
    },
    "q2": {
        "question": "Explain how VLOOKUP works and provide the formula to find the price in column D for an item named in cell A2. Also mention one limitation of VLOOKUP and show an INDEX/MATCH alternative.",
        "tags": ["lookup","vlookup","index_match"]
    },
    "q3": {
        "question": "How would you create a pivot table to show total sales by region from a table named 'SalesTable'?",
        "tags": ["pivot","data_analysis"]
    },
    "q4": {
        "question": "Describe how to highlight duplicate values in a column using conditional formatting.",
        "tags": ["conditional_formatting"]
    },
    "q5": {
        "question": "Write a short macro (VBA) to clear the contents of range A2:A100 on the active sheet.",
        "tags": ["macro","vba"]
    }
}

def make_eval_prompt(question_text: str, candidate_answer: str, tags: list):
    prompt = f"{INTRO}\n{EVAL_RUBRIC}\n\nQUESTION:\n{question_text}\n\nCANDIDATE_ANSWER:\n{candidate_answer}\n\nCONSTRAINTS: Return valid JSON only. Score per rubric 0-10. Tag the response with tags from: {tags}.\n"
    return prompt